title: Sahar Helali
email: helalisahar@gmail.com
description: Welcome to my portfolio website
#url: "/" 
#twitter_username:
#show_downloads : false
theme: jekyll-theme-minimam

#icon: /assets/img/icon.jpg
