title: Sahar Helali
email: helalisahar@gmail.com
description: Welcome to my portfolio website
"baseurl: "/" 
#url: "/" 
#twitter_username:
#show_downloads : false
theme : jekyll-theme-minimal 

#icon: /assets/img/icon.jpg
